version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Root project
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "auto-update"
    reviewers:
      - "user-github"
