name: Lint source code

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - run: python -m pip install --upgrade pip
    - run: python -m pip install .[lint]
    - run: ruff check . --output-format github
    - run: ruff format .
    - run: ruff format . --check

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - run: python -m pip install --upgrade pip
    - run: python -m pip install .[lint,test]
    - run: mypy . docs/ --exclude build/

  twine:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - run: python -m pip install --upgrade pip
    - run: python -m pip install --upgrade build twine
    - run: |
        rm -rf dist/
        python -m build .
        twine check dist/*
